### PR TITLE
Update Secret Ledger App to v2.34.2

### PR DESCRIPTION
**Pull request by SecretSaturn**
This update merges the audited upstream changes from https://github.com/LedgerHQ/app-cosmos for supporting Ledger Stax and adds extra string replacements for voting transactions for a better UX.

### CODE REVIEW

**Comment by cedelavergne-ledger** [comment]
After the merge on `develop`, the CI workflows output an error during **Stax** compilation:

```
...
[CC]   build/stax/obj/nbgl_navigation.o
/opt/stax-secure-sdk/lib_nbgl/src/nbgl_draw.c:18:10: fatal error: 'qrcodegen.h' file not found
#include "qrcodegen.h"
         ^~~~~~~~~~~~~

```

Please update the repository, probably `zxlib`, to fix the issue.
